### ISSUE TITLE
Your example does not work for me.

### ISSUE THREAD

**Issue by MariasStory** [waylonflinn/weblas#30]
Hi @waylonflinn,

It all looks very interesting and I would like to see your solution combined with neocortex.
I could not run your example in Chrome on Ubuntu. I have a build in I5 gpu and get:
"Bound framebuffer is not complete."
Error.

The error is in webgl.js:
if( gl.checkFramebufferStatus(gl.FRAMEBUFFER) != gl.FRAMEBUFFER_COMPLETE)
        throw new Error("Bound framebuffer is not complete.");

Am I doing something wrong there?

**Comment by MariasStory** [comment]
Sorry, the demo page that did not work is: http://waylonflinn.github.io/DeepBeliefSDK/

This example works on windows 10 with I5. I guess some gpu functionality are disabled in chrome on Ubuntu. I will check my settings.

BZW: Please cache the demo database, so it is not loaded every time.

**Comment by waylonflinn** [comment]
Thanks for the feedback. Caching the database is an excellent idea.
If you're thinking about porting neocortex, you might be interested in this project of mine:
https://github.com/waylonflinn/webnn

It's mission is to create a convolutional neural network that uses weblas in the browser. I'm hoping to return to work on it in the next week or so.

**Comment by MariasStory** [comment]
Hi @waylonflinn,

In linux I have this two options:
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled

Hope this helps to find the problem.

**Comment by MariasStory** [comment]
Hi @waylonflinn, it looks like your web example is working on Win with I5.

**Comment by waylonflinn** [comment]
@MariasStory glad to hear it. I'll close this. :smile:
