### ISSUE TITLE
lib/test.js should not be part of main package

### ISSUE THREAD

**Issue by transcranial** [waylonflinn/weblas#34]
Importing weblas from npm package gives the following error, as arrayloader is a devDependency:

```
ERROR in ./~/weblas/lib/test.js
Module not found: Error: Can't resolve 'arrayloader' in node_modules/weblas/lib'
 @ ./~/weblas/lib/test.js 2:10-32
 @ ./~/weblas/index.js
 @ ./src/Tensor.js
 @ ./src/index.js
 @ multi main
```

**Comment by waylonflinn** [comment]
Thanks Leon.
This should already be fixed in [master](https://github.com/waylonflinn/weblas/commit/02091dbcc5c003fb1f5304a38ae673684b4ea32c) (though the commit message doesn't mention it). I'm publishing a new version to npm right now.

**Comment by waylonflinn** [comment]
Can I close this?

**Comment by transcranial** [comment]
All good, thanks!
