### ISSUE TITLE
full tutorial ?

### ISSUE THREAD

**Issue by extremety1989** [waylonflinn/weblas#48]
Hey, i want to build reinforcement  ml, i already have basics on javascript,

how can i implement with you librairy ?

feedforward -> dot product ( inputs * weights of input to hidden  )  &&  dot product ( hidden *  weights of hidden to output  ) is it possible to generate random float numbers in glsl between -1 and 1 ?(like 0.4884484844, -0.848484848 etc..) ?

**Comment by waylonflinn** [comment]
Thanks for the feedback. We definitely need a tutorial. I'm working on a set of videos and written explanation to go along with them.

Regarding your specific question, you can find an example of a similar operation in the [webnn](https://github.com/waylonflinn/webnn) code.

Here's a link to the line implementing the matrix multiply:
https://github.com/waylonflinn/webnn/blob/master/lib/neuron.js#L57
